name: Nigiri pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt && pip3 install -r test_requirements.txt
          pip3 install -e .
      - name: Run Bitcoin Stack
        run: |
          docker compose --env-file .env.dev up -d bitcoin electrs
          bin/stack bitcoin -named createwallet wallet_name=default descriptors=false
          bin/stack bitcoin sethdseed true cSXteaZPxiDNEjtsgMhDKik5CL6YUc2hrEdkm51DrL85873UUFiQ
          bin/stack bitcoin generate 101
      - name: Run integration tests
        run: |
          pytest tests/integration/wallet_import_rescan.py
        